import Navbar from "./components/Navbar";
import Footer from "./components/footer";
import "./globals.css";
import "aos/dist/aos.css";

export const metadata = {
  title: "DJ/PRODUCER TEMPLATE",
  description: "Generated by create next app",
  author: "akocerke",
  keywords: "DJ, Producer, Music, Template, Next.js, Web Development",
  og: {
    title: "DJ/PRODUCER TEMPLATE",
    description: "Generated by create next app",
    image: "/path/to/your/image.jpg",
    url: "https://www.yourwebsite.com",
    type: "website",
  },
  twitter: {
    card: "summary_large_image", // oder "summary", je nach Bildgröße
    title: "DJ/PRODUCER TEMPLATE",
    description: "Generated by create next app",
    image: "/path/to/your/image.jpg",
    site: "@yourtwitterhandle"
  },
  robots: "index, follow",
  favicon: "/favicon.ico",
  lang: "de"

};

export default function RootLayout({ children }) {
  return (
    <html lang="de" className="dark"> {/* Dark Mode global aktiviert */}
      <body
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
